language: node_js
node_js:
  - 12.18.3
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - main
deploy:
  provider: heroku
  api_key:
    secure: ADD_API_KEY_HERE
  app:
    main: snake-snack-server
